pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        HOME = '.'
        //npm_config_cache = 'npm-cache'
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
       stage ('Pause to Test Docker for Debugging') {
       steps {
         echo "Taking approval from PROD manager"
         timeout(time: 7, unit: 'DAYS') {
         input message: 'Do you want to proceed to PROD?', submitter: 'admin,manager_userid'
         }
       }
     }

    }
}
